[package]
name = "fv-common-sys"
version = "5.0.8+1"
edition = "2021"
links = "fv-common"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.65"
cc = { version = "1.0", features = ["parallel"] }
